version: "3"

services:
  qiita:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18
    volumes:
      - ..:/workspace:delegated
      - /workspace/node_modules
    command: sleep infinity
